server:
  port: 8080
  servlet:
    context-path: /medicalProject

spring:
  application:
    name: medicalProject
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
